# Name of workflow
name: lint workflow
# Trigger workflow on all pr
on:
    pull_request:
        branches:
          - develop
          - main
# Jobs to carry out
jobs:
  test:
    # OS to run job
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Build the app
      - name: 🧰 install deps
        run: npm install
      - name: Run lint
        run: npm run eslint